# Generated by Django 4.1.1 on 2022-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("username", models.TextField()),
                ("code", models.TextField()),
                ("password", models.TextField()),
                ("email", models.TextField()),
            ],
            options={
                "ordering": ("created",),
            },
        ),
    ]
